### ISSUE TITLE
Multiple Custom Shapefiles 

### ISSUE THREAD

**Issue by JamesSlingsby** [HiDef-Aerial-Surveying/mCRM#4]
I am currently unable to add in multiple custom array shapefiles to carry out cumulative migratory collision assessments. However, this is something that is able to be done using the existing windfarm feature. Whenever I try to add in a second custom array shapefile it overwrites the existing one meaning only one can be added at a time using the custom array feature. Is this something that can be easily altered/fixed?

**Comment by grwhumphries** [comment]
Hey James - Keep your eye to this space - hopefully soon be able to update most of this.

**Comment by JamesSlingsby** [comment]
> Hey James - Keep your eye to this space - hopefully soon be able to update most of this.

Hi Grant - Thanks for the update on this, would you happen to have a more clear idea for when these changes might be implemented? It'd be great to know so we can plan with regards to various projects we have that are requiring this feature.

**Comment by grwhumphries** [comment]
Aiming for before Christmas. Fingers crossed!

**Comment by grwhumphries** [comment]
Hi James - just updating this now and the way to do this is to create a single shapefile with all your windfarms of interest.  You'll be able to see that in the updated README.
